To Find the patients which are closest

In [ ]:
import pandas as pd
import numpy as np
import math

In [ ]:
df_patient = pd.DataFrame({'HR' : [76, 74, 72, 78],
                           'BP' : [126, 120, 118, 136],
                           'Temp': [38, 38, 37.5, 37]})
df_patient


HR   BP  Temp
0  76  126  38.0
1  74  120  38.0
2  72  118  37.5
3  78  136  37.0

In [ ]:
A = np.array(df_patient)
A.shape
X=A[0,]
X

array([ 76., 126.,  38.])

In [ ]:
distance=[]
dis=0
for i in range(4):
  X=A[i,]
  for j in range(4):
      Y=A[j,]
      dis=math.dist(X,Y)
      distance.append(dis)
distance1=np.array(distance).reshape(4,4)
print(distance1)


[[ 0.          6.32455532  8.95823643 10.24695077]
 [ 6.32455532  0.          2.87228132 16.52271164]
 [ 8.95823643  2.87228132  0.         18.9802529 ]
 [10.24695077 16.52271164 18.9802529   0.        ]]


Hence, the nearest patients are 2 and 3.

To find patient which is farthest

In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
df_patient = pd.DataFrame({'HR' : [76, 74, 72, 78],
                           'BP' : [126, 120, 118, 136],
                           'Temp': [38, 38, 37.5, 37]})
df_patient

HR   BP  Temp
0  76  126  38.0
1  74  120  38.0
2  72  118  37.5
3  78  136  37.0

In [4]:
X = np.array(df_patient)
X.shape
X1=X[0,]
X2=X[1,]
X3=X[2,]
X4=X[3,]
X5=0.25*((X1+X2+X3+X4))
print(X5)
print(X5.dtype)
y=X[2,]
print(y)
print(y.dtype)


[ 75.    125.     37.625]
float64
[ 72.  118.   37.5]
float64


In [5]:
dis=0
distance=[]
X6=X5
for i in range(4):
  Y=X[i,]
  dis=math.dist(X6,Y)
  distance.append(dis)
  dis=0
print(distance)

[1.4630874888399532, 5.11279033405439, 7.6167988682910615, 11.41887144160928]


Hence, the farthest patient is 4.

To add Dummy patient details and calculate the point.

In [ ]:
dummy_row = {'HR':75, 'BP':140, 'Temp':38}
dummy_patient = df_patient.append(dummy_row, ignore_index=True)
print(dummy_patient)

   HR   BP  Temp
0  76  126  38.0
1  74  120  38.0
2  72  118  37.5
3  78  136  37.0
4  75  140  38.0


<ipython-input-30-f55796ed7f4e>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dummy_patient = df_patient.append(dummy_row, ignore_index=True)


In [ ]:
B = np.array(dummy_patient)
Q=B[4,]
Q

array([ 75., 140.,  38.])

In [ ]:
B = np.array(dummy_patient)
distance=[]
dis=0
i=0
j=0
for i in range(5):
  X=B[i,]
  for j in range(5):
      Y=B[j,]
      dis=math.dist(X,Y)
      distance.append(dis)
distance1=np.array(distance).reshape(5,5)
print(distance1)

[[ 0.          6.32455532  8.95823643 10.24695077 14.03566885]
 [ 6.32455532  0.          2.87228132 16.52271164 20.02498439]
 [ 8.95823643  2.87228132  0.         18.9802529  22.20923231]
 [10.24695077 16.52271164 18.9802529   0.          5.09901951]
 [14.03566885 20.02498439 22.20923231  5.09901951  0.        ]]


This technique can be used to detect a particular symptom/classify among patients based on a particular finding using distances between the points and see which ones are closer to each other.

Time compleity O(n*2)